### ISSUE TITLE
Card Search feature

### ISSUE THREAD

**Issue by Razor22Razor** [Slanfan/MTG-Tolaria#287] opened 2021-09-22 18:26 UTC
I would love the option to have all cards in my search come up as the original printing.  i dislike reprints.

**Comment by Slanfan** [comment] 2021-09-23 21:37
Please elaborate some more on this. As of today. All printings are shown in the result.

**Comment by Razor22Razor** [comment] 2021-10-02 05:38
![image](https://user-images.githubusercontent.com/91067529/135705028-936e902a-1e1b-4d0b-81ac-f32601cd03b9.png)

**Comment by Razor22Razor** [comment] 2021-10-02 05:39
As you can see, it only shows the garbage newest printing of the card I searched for.

**Comment by Slanfan** [comment] 2021-10-02 12:07
Thanks for the screenshot. This helps a lot. I will make sure Mr.Trike gets his shit straight.

**Comment by Razor22Razor** [comment] 2021-10-02 18:22
Excellent!R
-------- Original message --------From: Slanfan ***@***.***> Date: 2021-10-02  08:07  (GMT-05:00) To: Slanfan/MTG-Tolaria ***@***.***> Cc: Razor22Razor ***@***.***>, Author ***@***.***> Subject: Re: [Slanfan/MTG-Tolaria] Card Search feature (#287) 
Thanks for the screenshot. This helps a lot. I will make sure Mr.Trike gets his shit straight.

**Comment by Slanfan** [comment] 2021-10-04 23:17
Duplicate of https://github.com/Slanfan/MTG-Tolaria/issues/173

**Closed by Slanfan** 2021-10-04 23:17 UTC
Labels: duplicate
